art

diff --git a/.github/workflows/coverage.yml b/.github/workflows/coverage.yml
--- a/.github/workflows/coverage.yml
+++ b/.github/workflows/coverage.yml
@@ -119,40 +119,40 @@ jobs:
         run: |
           set -o pipefail
           newman run postman_collection.json -e postman_environment.json -d collectionRunnerData.json -n 1 --folder "Additional sundry tests" -r cli,htmlextra --reporter-cli-no-assertions --reporter-cli-no-console --reporter-htmlextra-showEnvironmentData --reporter-htmlextra-export ./newman/AdditionalSundryReport.html | grep -A18 '┌─────'
-      - name: Upload Newman artifact
-        id: artifact-upload
-        uses: actions/upload-artifact@v2
-        if: ${{ always() }}
-        with:
-          name: newman-htmlextra
-          path: ./test/api/newman
-      - name: Extract API container log
-        id: api-log-extract
-        if: ${{ always() }}
-        working-directory: ./test/api
-        run: |
-          docker logs stig-manager-api > api-log.json
-      - name: Upload API log artifact
-        uses: actions/upload-artifact@v2
-        id: api-log-upload
-        if: ${{ always() }}
-        with:
-          name: api-log
-          path: ./test/api/api-log.json
-      - name: Collect all container logs on failure
-        if: ${{ cancelled() || failure() }}
-        uses: jwalton/gh-docker-logs@54a2a89cd6a2c929525f26ca67a7a4857a5dc1d9 # pin@v1
-        with:
-          dest: './logs'
-      - name: Tar container logs
-        if: ${{ cancelled() || failure() }}
-        run: tar cvzf ./logs.tgz ./logs
-      - name: Upload container logs artifact
-        if: ${{ cancelled() || failure() }}
-        uses: actions/upload-artifact@master
-        with:
-          name: logs.tgz
-          path: ./logs.tgz   
+      # - name: Upload Newman artifact
+      #   id: artifact-upload
+      #   uses: actions/upload-artifact@v2
+      #   if: ${{ always() }}
+      #   with:
+      #     name: newman-htmlextra
+      #     path: ./test/api/newman
+      # - name: Extract API container log
+      #   id: api-log-extract
+      #   if: ${{ always() }}
+      #   working-directory: ./test/api
+      #   run: |
+      #     docker logs stig-manager-api > api-log.json
+      # - name: Upload API log artifact
+      #   uses: actions/upload-artifact@v2
+      #   id: api-log-upload
+      #   if: ${{ always() }}
+      #   with:
+      #     name: api-log
+      #     path: ./test/api/api-log.json
+      # - name: Collect all container logs on failure
+      #   if: ${{ cancelled() || failure() }}
+      #   uses: jwalton/gh-docker-logs@54a2a89cd6a2c929525f26ca67a7a4857a5dc1d9 # pin@v1
+      #   with:
+      #     dest: './logs'
+      # - name: Tar container logs
+      #   if: ${{ cancelled() || failure() }}
+      #   run: tar cvzf ./logs.tgz ./logs
+      # - name: Upload container logs artifact
+      #   if: ${{ cancelled() || failure() }}
+      #   uses: actions/upload-artifact@master
+      #   with:
+      #     name: logs.tgz
+      #     path: ./logs.tgz   
       - name: Stop STIG Manager
         id: api-stop
         run: |
