echo pid

diff --git a/.github/workflows/coverage.yml b/.github/workflows/coverage.yml
--- a/.github/workflows/coverage.yml
+++ b/.github/workflows/coverage.yml
@@ -13,13 +13,13 @@ on:
 # defaults:
 #   run:
 #     shell: bash      
-env:
-  STIGMAN_API_PORT: 64001
-  STIGMAN_DB_HOST: localhost
-  STIGMAN_DB_PORT: 3306
-  STIGMAN_DB_PASSWORD: stigman
-  STIGMAN_API_AUTHORITY: http://127.0.0.1:8080/auth/realms/stigman 
-  NODE_V8_COVERAGE: ./coverage-raw
+# env:
+#   STIGMAN_API_PORT: 64001
+#   STIGMAN_DB_HOST: localhost
+#   STIGMAN_DB_PORT: 3306
+#   STIGMAN_DB_PASSWORD: stigman
+#   STIGMAN_API_AUTHORITY: http://127.0.0.1:8080/auth/realms/stigman 
+#   NODE_V8_COVERAGE: ./coverage-raw
 
 jobs:
   # npm_audit:
@@ -57,38 +57,41 @@ jobs:
       - name: install dependencies
         working-directory: ./api/source
         run: npm ci   
-      - name: Run mock Keycloak
-        id: idp-run
-        working-directory: ./test/api/mock-keycloak
-        run: |
-          python3 -m http.server 8080 &
-      - name: Run MySQL container
-        id: mysql-run
-        run: |
-          docker run -d --name stig-manager-db \
-          -p 3306:3306 \
-          -e MYSQL_ROOT_PASSWORD=rootpw \
-          -e MYSQL_DATABASE=stigman \
-          -e MYSQL_USER=stigman \
-          -e MYSQL_PASSWORD=stigman \
-          mysql:8.0.21
-      - name: Install Newman reporter
-        id: newman-reporter-install
-        run: |
-          sudo npm install -g newman-reporter-htmlextra          
-      - name: Run STIG Manager app with c8 for coverage
-        id: api-run
+      - name: run app and get pid
         working-directory: ./api/source
-        run: |
-          nohup node index.js &
-      - name: Wait for bootstrap
-        run: for i in {1..10}; do [ $i -gt 1 ] && sleep 5; curl --output /dev/null --silent --fail http://localhost:64001/api/op/configuration && s=0 && break || s=$?; printf '.'; done; (exit $s)
-      - name: Run Newman Collection LoadTestData
-        id: newman-run-loadTestData
-        working-directory: ./test/api
-        run: |
-          set -o pipefail
-          newman run postman_collection.json -e postman_environment.json -d collectionRunnerData.json -n 1 --folder LoadTestData -r cli,htmlextra  --reporter-cli-no-assertions --reporter-cli-no-console --reporter-htmlextra-showOnlyFails --reporter-htmlextra-export ./newman/dataPreloadReport.html | grep -A18 '┌─────'
+        run: sh -c 'echo $$; exec npm run start'          
+      # - name: Run mock Keycloak
+      #   id: idp-run
+      #   working-directory: ./test/api/mock-keycloak
+      #   run: |
+      #     python3 -m http.server 8080 &
+      # - name: Run MySQL container
+      #   id: mysql-run
+      #   run: |
+      #     docker run -d --name stig-manager-db \
+      #     -p 3306:3306 \
+      #     -e MYSQL_ROOT_PASSWORD=rootpw \
+      #     -e MYSQL_DATABASE=stigman \
+      #     -e MYSQL_USER=stigman \
+      #     -e MYSQL_PASSWORD=stigman \
+      #     mysql:8.0.21
+      # - name: Install Newman reporter
+      #   id: newman-reporter-install
+      #   run: |
+      #     sudo npm install -g newman-reporter-htmlextra          
+      # - name: Run STIG Manager app with c8 for coverage
+      #   id: api-run
+      #   working-directory: ./api/source
+      #   run: |
+      #     nohup node index.js &
+      # - name: Wait for bootstrap
+      #   run: for i in {1..10}; do [ $i -gt 1 ] && sleep 5; curl --output /dev/null --silent --fail http://localhost:64001/api/op/configuration && s=0 && break || s=$?; printf '.'; done; (exit $s)
+      # - name: Run Newman Collection LoadTestData
+      #   id: newman-run-loadTestData
+      #   working-directory: ./test/api
+      #   run: |
+      #     set -o pipefail
+      #     newman run postman_collection.json -e postman_environment.json -d collectionRunnerData.json -n 1 --folder LoadTestData -r cli,htmlextra  --reporter-cli-no-assertions --reporter-cli-no-console --reporter-htmlextra-showOnlyFails --reporter-htmlextra-export ./newman/dataPreloadReport.html | grep -A18 '┌─────'
       # - name: Run Newman Collection GETS
       #   id: newman-run-gets
       #   if: steps.newman-run-loadTestData.conclusion == 'success'
@@ -117,13 +120,13 @@ jobs:
       #   run: |
       #     set -o pipefail
       #     newman run postman_collection.json -e postman_environment.json -d collectionRunnerData.json -n 1 --folder "LVL1 cross-boundary tests" -r cli,htmlextra --reporter-cli-no-assertions --reporter-cli-no-console --reporter-htmlextra-showEnvironmentData --reporter-htmlextra-export ./newman/lvl1Report.html | grep -A18 '┌─────'
-      - name: Run Newman Collection Additional Sundry Tests
-        id: newman-run-additional-sundry
-        if: steps.newman-run-loadTestData.conclusion == 'success'
-        working-directory: ./test/api
-        run: |
-          set -o pipefail
-          newman run postman_collection.json -e postman_environment.json -d collectionRunnerData.json -n 1 --folder "Additional sundry tests" -r cli,htmlextra --reporter-cli-no-assertions --reporter-cli-no-console --reporter-htmlextra-showEnvironmentData --reporter-htmlextra-export ./newman/AdditionalSundryReport.html | grep -A18 '┌─────'
+      # - name: Run Newman Collection Additional Sundry Tests
+      #   id: newman-run-additional-sundry
+      #   if: steps.newman-run-loadTestData.conclusion == 'success'
+      #   working-directory: ./test/api
+      #   run: |
+      #     set -o pipefail
+      #     newman run postman_collection.json -e postman_environment.json -d collectionRunnerData.json -n 1 --folder "Additional sundry tests" -r cli,htmlextra --reporter-cli-no-assertions --reporter-cli-no-console --reporter-htmlextra-showEnvironmentData --reporter-htmlextra-export ./newman/AdditionalSundryReport.html | grep -A18 '┌─────'
       # - name: Upload Newman artifact
       #   id: artifact-upload
       #   uses: actions/upload-artifact@v2
@@ -158,42 +161,42 @@ jobs:
       #   with:
       #     name: logs.tgz
       #     path: ./logs.tgz   
-      - name: list processes
-        run: ps -ef
+      # - name: list processes
+      #   run: ps -ef
+      # # - name: Stop STIG Manager
+      # #   id: api-stop
+      # #   run: sudo kill-port --graceful -p 64001  
       # - name: Stop STIG Manager
+      #   if: steps.newman-run-additional-sundry.conclusion == 'success'
       #   id: api-stop
-      #   run: sudo kill-port --graceful -p 64001  
-      - name: Stop STIG Manager
-        if: steps.newman-run-additional-sundry.conclusion == 'success'
-        id: api-stop
-        run: sudo killall -15 node
-      - name: list processes2
-        if: steps.api-stop.conclusion == 'success'
+      #   run: sudo killall -15 node
+      # - name: list processes2
+      #   if: steps.api-stop.conclusion == 'success'
 
-        run: ps -ef 
-      - name: check directory1
-        if: steps.api-stop.conclusion == 'success'
-        working-directory: ./api/source/coverage
-        run: |
-          pwd
-          ls -ltr
-      - name: check directory1
-        working-directory: ./api/source/coverage/tmp
-        run: |
-          pwd
-          ls -ltr         
-      - name: Upload coverage artifact
-        id: artifact-upload
-        uses: actions/upload-artifact@v2
-        if: ${{ always() }}
-        with:
-          name: coverage-report
-          path: ./api/source/coverage
-      - name: Upload coverage artifact
-        id: artifact-upload2
-        uses: actions/upload-artifact@v2
-        if: ${{ always() }}
-        with:
-          name: coverage-report-raw
-          path: ./coverage-raw          
+      #   run: ps -ef 
+      # - name: check directory1
+      #   if: steps.api-stop.conclusion == 'success'
+      #   working-directory: ./api/source/coverage
+      #   run: |
+      #     pwd
+      #     ls -ltr
+      # - name: check directory1
+      #   working-directory: ./api/source/coverage/tmp
+      #   run: |
+      #     pwd
+      #     ls -ltr         
+      # - name: Upload coverage artifact
+      #   id: artifact-upload
+      #   uses: actions/upload-artifact@v2
+      #   if: ${{ always() }}
+      #   with:
+      #     name: coverage-report
+      #     path: ./api/source/coverage
+      # - name: Upload coverage artifact
+      #   id: artifact-upload2
+      #   uses: actions/upload-artifact@v2
+      #   if: ${{ always() }}
+      #   with:
+      #     name: coverage-report-raw
+      #     path: ./coverage-raw          
 
